# Generated by Django 3.0.2 on 2020-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('stock_no', models.IntegerField()),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
